import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders The Director Game's complete opening state", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>The Director Game<\/title>/i);
  assert.match(html, /The Director Game/i);
  assert.equal((html.match(/class="movie-ticket /g) ?? []).length, 10);
  assert.equal((html.match(/class="director-slot is-active/g) ?? []).length, 2);
  assert.equal((html.match(/class="director-slot is-empty/g) ?? []).length, 3);
  assert.equal((html.match(/data-drop-target="director"/g) ?? []).length, 2);
  assert.equal((html.match(/data-drop-target="false"/g) ?? []).length, 3);
  assert.equal((html.match(/data-socket-count="3"/g) ?? []).length, 2);
  assert.equal((html.match(/class="director-socket\b/g) ?? []).length, 6);
  assert.equal((html.match(/class="game-loop-step\b/g) ?? []).length, 3);
  assert.match(html, /class="screen-instruction match-route"[^>]*aria-label="Drag a movie ticket to a director"/i);
  assert.match(html, /MOVIE TICKET[\s\S]*?DIRECTOR/i);
  assert.match(html, /MATCH 3 FILMS/i);
  assert.match(html, /Complete a director’s set/i);
  assert.match(html, /CLEAR DIRECTORS/i);
  assert.match(html, /Finished directors leave the board/i);
  assert.match(html, /DON’T FILL THE BOARD/i);
  assert.match(html, /Incoming director \+ 5 full slots = Game Over/i);
  assert.match(html, /Start sorting/i);
  assert.doesNotMatch(html, /Hold for a future slot/i);
  assert.match(html, /Director capacity/i);
  assert.match(html, /class="hud-panel capacity-panel pressure-normal"/i);
  assert.match(html, /class="capacity-state">normal</i);
  assert.match(html, /aria-label="Director capacity 2 of 5\. Pressure normal\."/i);
  assert.doesNotMatch(html, /class="capacity-leds"/i);
  assert.match(html, /class="hud-panel next-director-panel arrival-safe"/i);
  assert.match(html, /class="next-director-label">Next director in</i);
  assert.match(html, /class="next-director-display"/i);
  assert.match(html, /class="hud-panel score-panel multiplier-1"/i);
  assert.match(html, /×(?:<!-- -->)?1/i);
  assert.match(html, /Stage (?:<!-- -->)?1(?:<!-- -->)? · Total score/i);
  assert.match(html, /Victory area/i);
  assert.match(html, /Hint shop/i);
  assert.match(html, /Hints for:/i);
  assert.match(html, /Select a movie or director/i);
  assert.match(html, /Frame check/i);
  assert.equal((html.match(/aria-label="Open director hints for /g) ?? []).length, 2);
  assert.match(html, /Open file \+/i);
  const scoreIndex = html.indexOf("score-panel");
  const capacityIndex = html.indexOf("capacity-panel");
  const nextDirectorIndex = html.indexOf("next-director-panel");
  const hintIndex = html.indexOf("hint-panel");
  const victoryIndex = html.indexOf("victory-panel");
  assert.ok(scoreIndex >= 0 && scoreIndex < capacityIndex);
  assert.ok(capacityIndex < nextDirectorIndex && nextDirectorIndex < hintIndex && hintIndex < victoryIndex);
  assert.doesNotMatch(html.slice(scoreIndex, capacityIndex), /coin-readout/);
  assert.match(html.slice(hintIndex, victoryIndex), /coin-readout/);
  assert.match(html.slice(hintIndex, victoryIndex), /4 coins/);
  assert.match(html.slice(hintIndex, victoryIndex), /aria-live="polite"[^>]*aria-atomic="true"/);
  assert.match(html, /CRT FX/i);
  assert.match(html, /How to play/i);
  assert.doesNotMatch(html, /Cine-meter|score-meter|booster pack|Start round/i);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape/i);
});

test("keeps the CRT game local, data-driven and answer-safe", async () => {
  const [page, shell, cards, tutorial, hud, coinFx, completionArchive, rankPopup, stageResults, visualHintOverlay, engine, directorHints, genreColors, styles, data, expanded, packageJson] = await Promise.all([
    readFile(new URL("../app/components/DirectorGame.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/CrtTelevision.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/ConstellationCard.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/GameLoopTutorial.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/GameHud.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/CoinRewardFx.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/CompletionArchiveSequence.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/RankPopup.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/StageResultsOverlay.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/VisualHintOverlay.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/data/game-engine.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/data/director-hints.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/data/genre-colors.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../app/data/directors.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/data/expanded-directors.ts", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
  ]);

  assert.match(page, /attemptAssignment/);
  assert.match(page, /directorAtPoint/);
  assert.match(page, /if \(targetDirectorId\) resolveAssignment/);
  assert.match(page, /onPointerCancel=\{cancelDragging\}/);
  assert.match(page, /onLostPointerCapture=\{cancelDragging\}/);
  assert.doesNotMatch(page, /onPointerCancel=\{stopDragging\}/);
  assert.match(page, /isReceiving=\{Boolean\(draggingFilmId\)\}/);
  assert.match(page, /setSelectedFilmId\(drag\.filmId\)/);
  assert.match(page, /returnPosition\?: Position/);
  assert.match(page, /setPositions\(\(current\) => \(\{ \.\.\.current, \[filmId\]: returnPosition \}\)\)/);
  assert.match(page, /ticket stays on the table and remains playable/);
  assert.doesNotMatch(page, /wrongMovieReappearDelay|poofingFilmId/);
  assert.match(page, /newlyVisibleMovieIds/);
  assert.match(page, /launchCoinReward\(outcome\.coinsAwarded/);
  assert.match(page, /outcome\.comboBonusCoins/);
  assert.match(page, /outcome\.multiplier/);
  assert.match(page, /startNextStage\(game\)/);
  assert.match(page, /<StageResultsOverlay game=\{game\}/);
  assert.match(page, /hintContextFilmId/);
  assert.match(page, /hintContextDirectorId/);
  assert.match(page, /purchaseDirectorHint/);
  assert.match(page, /buyDirectorHint/);
  assert.match(page, /reopenDirectorHint/);
  assert.match(page, /visualHintKey/);
  assert.match(page, /openVisualHint/);
  assert.match(page, /<VisualHintOverlay/);
  assert.match(page, /wrongStreakRef\.current >= 4/);
  assert.match(page, /hintRescueCooldownMoveRef\.current = outcome\.state\.moveCount \+ 8/);
  assert.match(page, /setHintRescueVisible\(true\)/);
  assert.match(page, /setAutoOpenHint\(\{ filmId: targetFilmId, type \}\)/);
  assert.match(page, /setLastHintByFilm/);
  assert.match(page, /4200/);
  assert.match(page, /<CoinRewardLayer events=\{coinRewards\}/);
  assert.match(page, /setArchiveSequence\(/);
  assert.match(page, /playSound\("punch"\)/);
  assert.match(page, /\[70, 170, 270\]\.forEach/);
  assert.match(page, /schedule\(\(\) => applyOutcome\(outcome\), applyDelay\)/);
  assert.match(page, /isArchiving=\{archiveSequence\?\.directorId === directorId\}/);
  assert.match(page, /<CompletionArchiveSequence directorName=\{archiveSequence\.directorName\} filmTitles=\{archiveSequence\.filmTitles\}/);
  assert.doesNotMatch(page, /completionBurst|completion-burst|completion-ticket/);
  assert.match(page, /Color = Genre/i);
  assert.match(page, /GENRE_LEGEND\.map/);
  assert.match(page, /Color equals genre: Romance pink, Comedy yellow, Drama blue, Horror red, Sci-Fi cyan, Fantasy green, Crime and Thriller purple/);
  assert.match(page, /youtube-nocookie\.com\/embed/);
  assert.doesNotMatch(page, /selectedDirector|correctDirectorId|auto.?fil/i);
  assert.match(shell, /className="crt-tv"/);
  assert.match(shell, /className="crt-screen"/);
  assert.match(shell, /className="crt-scanlines" aria-hidden="true"/);
  assert.match(cards, /ticket-stickers/);
  assert.match(cards, /is-auto-open/);
  assert.match(cards, /is-expanded/);
  assert.match(cards, /setIsExpanded\(\(current\) => !current\)/);
  assert.match(cards, /onMouseLeave=\{\(\) => setIsExpanded\(false\)\}/);
  assert.match(cards, /aria-expanded=\{isVisual \? undefined : isExpanded \|\| isAutoOpen\}/);
  assert.match(cards, /is-new/);
  assert.match(cards, /isLatest=\{sticker\.type === lastHintType\}/);
  assert.match(cards, /onMouseEnter=\{\(\) => onHintContext\(film\.id\)\}/);
  assert.match(cards, /onFocusCapture=\{\(\) => onHintContext\(film\.id\)\}/);
  assert.match(cards, /aria-pressed=\{isSelected\}/);
  assert.match(cards, /PUNCH_HOLE_POSITIONS/);
  assert.match(cards, /runtime\.punchCount/);
  assert.match(cards, /"--ticket-hole-mask": punchMask \|\| "linear-gradient\(#000 0 0\)"/);
  assert.match(cards, /ticket-punches/);
  assert.match(cards, /No match · Punched/);
  assert.match(cards, /director-sockets/);
  assert.match(cards, /director-context-button/);
  assert.match(cards, /Open director hints for/);
  assert.match(cards, /Open file \+/);
  assert.match(cards, /Open full-screen/);
  assert.match(cards, /onOpenVisualHint/);
  assert.match(cards, /director-socket/);
  assert.match(cards, /data-drop-target="false"/);
  assert.match(cards, /data-drop-target="director"/);
  assert.match(cards, /data-socket-count=\{socketCount\}/);
  assert.match(cards, /isHighlighted = dropState === "neutral" && !isFilled/);
  assert.match(cards, /const displayGenre = genreFamily\(film\.genre\)/);
  assert.match(cards, /"--ticket-accent": genreColor\(film\.genre\)/);
  assert.doesNotMatch(cards, /film\.accent/);
  assert.match(cards, /className="ticket-meta"/);
  assert.match(cards, /<span>\{displayGenre\}<\/span><i aria-hidden="true">·<\/i><b>\{film\.year\}<\/b>/);
  assert.doesNotMatch(cards, /className="ticket-year"/);
  assert.match(cards, /<span>\{film\.title\}<\/span><small>\{film\.year\}<\/small>/);
  assert.match(cards, /`\$\{film\.title\} \(\$\{film\.year\}\)`/);
  assert.doesNotMatch(cards, /waiting_for_director|Hold for a future slot/);
  assert.doesNotMatch(cards, /sticker-frames|commons\.wikimedia\.org/);
  assert.match(visualHintOverlay, /role="dialog" aria-modal="true"/);
  assert.match(visualHintOverlay, /event\.key === "Escape"/);
  assert.match(visualHintOverlay, /event\.key === "Tab"/);
  assert.match(visualHintOverlay, /closeButtonRef\.current\?\.focus\(\)/);
  assert.match(visualHintOverlay, /Movie title/);
  assert.match(visualHintOverlay, /visual-hint-content/);
  assert.match(visualHintOverlay, /visual-hint-close/);
  assert.match(visualHintOverlay, /Close \$\{sticker\.label\} for \$\{film\.title\}/);
  assert.match(visualHintOverlay, /type === "movieIdentification" \? frames\.slice\(0, 1\) : frames\.slice\(0, 3\)/);
  assert.match(visualHintOverlay, /decoding="async"/);
  assert.match(visualHintOverlay, /draggable=\{false\}/);
  assert.match(visualHintOverlay, /commons\.wikimedia\.org\/w\/api\.php/);
  assert.match(visualHintOverlay, /<h2 id=\{titleId\}>\{film\.title\}<\/h2>[\s\S]*?<p>\{sticker\.label\}<\/p>[\s\S]*?visual-hint-content[\s\S]*?visual-hint-close/);
  assert.match(tutorial, /GAME_LOOP_BEATS\.map/);
  assert.equal((tutorial.match(/title: "/g) ?? []).length, 3);
  assert.match(tutorial, /MATCH 3 FILMS/);
  assert.match(tutorial, /CLEAR DIRECTORS/);
  assert.match(tutorial, /DON’T FILL THE BOARD/);
  assert.doesNotMatch(tutorial, /<p\b|Trust the release|Spend coins carefully|Hint stickers stay attached/);
  assert.match(hud, /HINT_TYPES\.map/);
  assert.match(hud, /DIRECTOR_HINT_TYPES\.map/);
  assert.match(hud, /DIRECTOR HINTS/);
  assert.match(hud, /MOVIE HINTS/);
  assert.match(hud, /Hints for:/);
  assert.match(hud, /hintContextFilm\?\.title/);
  assert.match(hud, /hintContextDirector\?\.name/);
  assert.match(hud, /director-hint-reveal/);
  assert.match(hud, /Build a director file without revealing the three movie answers/);
  assert.match(hud, /hintRescueVisible/);
  assert.match(hud, /Four misses—try one clue/);
  assert.match(hud, /className="hint-price"/);
  assert.match(hud, /`\$\{cost\} ●`/);
  assert.match(hud, /hintCostForMovie/);
  assert.match(hud, /canUseEliminationHint/);
  assert.match(hud, /USE AGAIN/);
  assert.match(hud, /ONE CANDIDATE LEFT/);
  assert.match(hud, /EMERGENCY ANSWER/);
  assert.match(hud, /PANIC OPTION/);
  assert.match(hud, /GAME_CONFIG\.emergencyAnswerScoreMultiplier/);
  assert.match(hud, /is-emergency/);
  assert.match(hud, /directorCount >= 5 \? "critical" : directorCount === 4 \? "warning" : directorCount === 3 \? "noticeable" : "normal"/);
  assert.match(hud, /Board pressure/);
  assert.match(hud, /capacity-state/);
  assert.doesNotMatch(hud, /capacity-leds/);
  assert.match(hud, /arrivalState = isCleanup \? "cleanup"/);
  assert.match(hud, /arrival-\$\{arrivalState\}/);
  assert.match(hud, /multiplier-badge/);
  assert.match(hud, /ON FIRE/);
  assert.match(hud, /STEAMING/);
  assert.match(hud, /CLEAR THE TABLE/);
  assert.match(hud, /aria-live="polite"/);
  assert.match(hud, /isLastSafeMove = !isCleanup && directorCount === GAME_CONFIG\.maximumActiveDirectors - 1 && game\.nextDirectorIn === 1/);
  assert.match(hud, /next-director-panel/);
  assert.match(hud, /Last safe move · Clear a director now/);
  assert.match(hud, /Choose this movie&apos;s director/);
  assert.match(hud, /Assign \$\{selectedFilm\.title\} to/);
  assert.ok(hud.indexOf("hint-panel") < hud.indexOf("victory-panel"));
  assert.match(hud, /hint-shop-intro/);
  assert.match(hud, /aria-atomic="true"/);
  assert.match(coinFx, /Array\.from\(\{ length: event\.amount \}/);
  assert.match(coinFx, /COIN_STAGGER_MS/);
  assert.match(coinFx, /event\.bonusAmount/);
  assert.match(coinFx, /coin-combo-pop/);
  assert.match(coinFx, /FROM ×/);
  assert.match(completionArchive, /3 films matched/i);
  assert.match(completionArchive, /filmTitles\.slice\(0, 3\)\.map/);
  assert.match(completionArchive, /ARCHIVED/);
  assert.match(completionArchive, /To Victory Area/);
  assert.doesNotMatch(rankPopup, /rank-rays/);
  assert.match(stageResults, /Stage completed!/);
  assert.match(stageResults, /Stage score/);
  assert.match(stageResults, /Total score/);
  assert.match(stageResults, /Best combo/);
  assert.match(stageResults, /Highest multiplier/);
  assert.match(stageResults, /Reward bay/);
  assert.match(stageResults, /window\.setInterval/);
  assert.match(engine, /coinsAwarded: config\.correctMatchCoins \+ comboBonusCoins/);
  assert.match(engine, /coinsAwarded: 0/);
  assert.match(engine, /punchCount: movie\.punchCount \+ 1/);
  assert.match(engine, /newlyVisibleMovieIds: \[\]/);
  assert.doesNotMatch(engine, /waiting_to_reappear|wrongMovieReappearDelay/);
  assert.match(engine, /visibleMovieCount:\s*10/);
  assert.match(engine, /maximumActiveDirectors:\s*5/);
  assert.match(engine, /stageDirectorCount:\s*10/);
  assert.doesNotMatch(engine, /targetDirectorCompletions/);
  assert.match(engine, /startingCoins:\s*4/);
  assert.match(engine, /comboTwoMultiplierAt:\s*4/);
  assert.match(engine, /comboThreeMultiplierAt:\s*6/);
  assert.match(engine, /comboTwoCoinBonus:\s*1/);
  assert.match(engine, /comboThreeCoinBonus:\s*2/);
  assert.match(engine, /status: "stage_complete"/);
  assert.match(engine, /export function startNextStage/);
  assert.match(engine, /stageSet\.has\(movie\.ownerDirectorId\)/);
  assert.match(engine, /eliminationHintCosts:\s*\[2, 3, 5\]/);
  assert.match(engine, /emergencyAnswerScoreMultiplier:\s*0\.5/);
  assert.match(engine, /directorHintCosts/);
  assert.match(engine, /export function purchaseDirectorHint/);
  assert.match(engine, /directorHints:/);
  assert.match(engine, /movie\.hints\.directAnswer \? config\.emergencyAnswerScoreMultiplier : 1/);
  assert.match(engine, /Correct director: \$\{owner\.name\}/);
  assert.match(engine, /type !== "elimination" && movie\.hints\[type\]/);
  assert.match(engine, /directorId !== movie\.ownerDirectorId/);
  assert.match(engine, /remainingDirectorCandidates/);
  assert.match(directorHints, /origin: "Origin"/);
  assert.match(directorHints, /careerPeriod: "Career period"/);
  assert.match(directorHints, /genreTendency: "Genre tendency"/);
  assert.match(directorHints, /thematicDNA: "Thematic DNA"/);
  assert.match(directorHints, /styleNote: "Style note"/);
  assert.match(directorHints, /knownFor: "Known for"/);
  assert.equal((directorHints.match(/^ {2}"?[a-z0-9-]+"?: profile\(/gm) ?? []).length, 60);
  assert.equal((genreColors.match(/^ {2}["A-Z]/gm) ?? []).length, 7);
  assert.match(genreColors, /Romance: "#ff7eb6"/);
  assert.match(genreColors, /Comedy: "#ffd84a"/);
  assert.match(genreColors, /Drama: "#5d8dff"/);
  assert.match(genreColors, /Horror: "#ff504e"/);
  assert.match(genreColors, /"Sci-Fi": "#61eee0"/);
  assert.match(genreColors, /Fantasy: "#8fdc62"/);
  assert.match(genreColors, /"Crime\/Thriller": "#b07cff"/);
  assert.equal((engine.match(/title: "/g) ?? []).length, 6);
  assert.match(styles, /\.crt-tv\s*\{/);
  assert.match(styles, /\.crt-screen\s*\{/);
  assert.match(styles, /aspect-ratio:\s*16\s*\/\s*9/);
  assert.match(styles, /height:\s*100dvh/);
  assert.doesNotMatch(styles, /\.crt-screen\s*\{[^}]*min-height:\s*clamp\(610px/s);
  assert.match(styles, /pointer-events:\s*none/);
  assert.match(styles, /\.director-slot\.is-empty\s*\{[^}]*pointer-events:\s*none/s);
  assert.match(styles, /\.director-slot\.is-active\.is-receiving\s*\{/);
  assert.match(styles, /\.director-slot\.is-active\.is-neutral\s+\.director-socket\.is-open/);
  assert.match(styles, /\.director-slot\.is-archiving\s*\{[^}]*animation:\s*director-archive-exit/s);
  assert.match(styles, /\.director-socket\.is-ready/);
  assert.doesNotMatch(styles, /\.director-board-screen\s*\{[^}]*touch-action:\s*none/s);
  assert.match(styles, /contain:\s*layout paint/);
  assert.match(styles, /\.genre-rule/);
  assert.match(styles, /\.hint-panel\.is-rescue\s*\{[^}]*animation:\s*hint-shop-rescue 1s ease-in-out 4/s);
  assert.match(styles, /\.hint-sticker\.is-new\s*\{[^}]*animation:\s*hint-sticker-plop/s);
  assert.match(styles, /\.hint-sticker\.is-auto-open \.hint-sticker-popover/);
  assert.match(styles, /\.hint-sticker\.is-expanded \.hint-sticker-popover/);
  assert.match(styles, /\.hint-sticker-popover\s*\{[^}]*visibility:\s*hidden[^}]*opacity:\s*0[^}]*transition:/s);
  assert.doesNotMatch(styles, /\.movie-ticket:(?:hover|focus)[^,{]*\.hint-sticker\.is-latest \.hint-sticker-popover/);
  assert.doesNotMatch(styles, /\.movie-ticket\.is-selected \.hint-sticker\.is-latest \.hint-sticker-popover/);
  assert.match(styles, /\.hint-context\.has-movie strong/);
  assert.match(styles, /\.hint-context\.has-director strong/);
  assert.match(styles, /\.director-hint-reveal/);
  assert.match(styles, /\.director-slot\.is-selected/);
  assert.match(styles, /\.visual-hint-layer\s*\{[^}]*inset:\s*0[^}]*background:\s*rgba\(2,9,12,\.82\)/s);
  assert.match(styles, /\.visual-hint-dialog/);
  assert.match(styles, /\.visual-hint-content\.is-frame-check/);
  assert.match(styles, /\.visual-hint-content\.is-visual-dna/);
  assert.match(styles, /\.visual-hint-close\s*\{[^}]*top:[^}]*width:\s*clamp\(54px/s);
  assert.match(styles, /\.hint-price b/);
  assert.match(styles, /\.hint-grid button\.is-repeatable/);
  assert.match(styles, /\.hint-grid button\.is-emergency/);
  assert.match(styles, /\.hint-grid button\.is-emergency \.hint-icon/);
  assert.match(styles, /\.score-panel\.multiplier-2 \.multiplier-badge/);
  assert.match(styles, /\.score-panel\.multiplier-3 \.multiplier-badge/);
  assert.match(styles, /\.next-director-panel\.arrival-warm/);
  assert.match(styles, /\.next-director-panel\.arrival-hot/);
  assert.match(styles, /\.next-director-panel\.arrival-critical/);
  assert.match(styles, /\.next-director-display strong\s*\{[^}]*color:\s*var\(--arrival-color\)/s);
  assert.match(styles, /\.archive-ticket-stage\s*\{[^}]*animation:\s*archive-stack-flight/s);
  assert.match(styles, /@keyframes archive-ticket-snap/);
  assert.match(styles, /@keyframes archive-punch-hit/);
  assert.match(styles, /@keyframes archive-stack-flight/);
  assert.match(styles, /@keyframes director-archive-exit/);
  assert.doesNotMatch(styles, /rank-rays|rays-spin|completion-burst|completion-ticket/);
  assert.doesNotMatch(styles, /\.capacity-leds/);
  assert.match(styles, /\.stage-results-overlay/);
  assert.match(styles, /\.stage-score-transfer/);
  assert.match(styles, /\.stage-results-grid/);
  assert.match(styles, /\.coin-combo-pop/);
  assert.match(styles, /@keyframes hint-sticker-plop/);
  assert.match(styles, /@keyframes hint-shop-rescue/);
  assert.match(styles, /\.ticket-meta\s*\{/);
  assert.doesNotMatch(styles, /\.ticket-meta[^}]*display:\s*none/s);
  assert.match(styles, /\.director-mini-stack button small/);
  assert.equal((styles.match(/animation:[^;{}]*infinite/g) ?? []).length, 1);
  assert.match(styles, /\.next-director-panel\.is-last-safe\s*\{[^}]*animation:\s*next-director-safe-pulse 2s ease-in-out infinite/s);
  assert.doesNotMatch(styles, /@keyframes crt-noise/);
  assert.match(styles, /@keyframes tutorial-socket-fill/);
  assert.match(styles, /@keyframes tutorial-director-clear/);
  assert.match(styles, /@keyframes tutorial-board-pressure/);
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.game-loop-step/);
  assert.match(styles, /@keyframes ticket-plop/);
  assert.match(styles, /@keyframes ticket-reject-return/);
  assert.match(styles, /@keyframes ticket-punch-in/);
  assert.match(styles, /\.ticket-punches i/);
  assert.match(styles, /\.movie-ticket::before[^}]*-webkit-mask-image:\s*var\(--ticket-hole-mask\)[^}]*mask-composite:\s*intersect/s);
  assert.doesNotMatch(styles, /\.movie-ticket\.is-rejected[^}]*opacity:\s*0/s);
  assert.match(styles, /@keyframes director-plop/);
  assert.match(styles, /@keyframes coin-flight/);
  assert.match(styles, /@keyframes coin-readout-pop/);
  assert.match(styles, /\.capacity-panel\.pressure-noticeable/);
  assert.match(styles, /\.capacity-panel\.pressure-warning/);
  assert.match(styles, /\.capacity-panel\.pressure-critical/);
  assert.match(styles, /\.capacity-state/);
  assert.match(styles, /@keyframes next-director-safe-pulse/);
  assert.match(styles, /@keyframes next-director-safe-pulse[\s\S]*?background-color:\s*#66333a/);
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.next-director-panel\.is-last-safe\s*\{[^}]*animation:\s*none/s);
  assert.match(styles, /\.director-slots\s*\{[^}]*top:\s*clamp\(116px,\s*27\.5%,\s*160px\)/s);
  assert.match(styles, /@keyframes rank-pop/);
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)/);
  assert.doesNotMatch(styles, /\.score-meter/);
  assert.equal((data.match(/name: "/g) ?? []).length, 10);
  assert.equal((expanded.match(/^ {2}d\(/gm) ?? []).length, 50);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
});
