import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the Reel Challenge main menu", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>Reel Challenge! — The Movie Game Show<\/title>/i);
  assert.match(html, /class="game-menu game-home-menu"/i);
  assert.match(html, /REEL[\s\S]*?CHALLENGE!/i);
  assert.match(html, /The movie game show/i);
  assert.match(html, /New run/i);
  assert.match(html, /Select game/i);
  assert.match(html, /Director, Timeline, Cast Call, or Cinema Map/i);
  assert.match(html, /4 games online/i);
  assert.match(html, /CRT FX/i);
  assert.doesNotMatch(html, /The Director Game/i);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape/i);
});

test("keeps the CRT game local, data-driven and answer-safe", async () => {
  const [page, menu, shell, cards, tutorial, timeline, hud, coinFx, directorArrivalFx, completionArchive, rankPopup, stageResults, dossier, engine, difficulty, directorHints, genreColors, styles, data, expanded, packageJson] = await Promise.all([
    readFile(new URL("../app/components/DirectorGame.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/GameMenu.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/CrtTelevision.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/ConstellationCard.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/GameLoopTutorial.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/ReleaseTimelineStage.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/GameHud.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/CoinRewardFx.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/DirectorArrivalFx.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/CompletionArchiveSequence.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/RankPopup.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/StageResultsOverlay.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/MovieDossierOverlay.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/data/game-engine.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/data/director-difficulty.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/data/director-hints.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/data/genre-colors.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../app/data/directors.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/data/expanded-directors.ts", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
  ]);
  const [castCallGame, castCallCards, castCallHud, castCallEngine, castCallData] = await Promise.all([
    readFile(new URL("../app/components/CastCallGame.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/CastCallCards.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/CastCallHud.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/data/cast-call-engine.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/data/cast-call-data.ts", import.meta.url), "utf8"),
  ]);
  const [cinemaMapGame, cinemaWorldMap, movieGeoTicket, cinemaMapHud, cinemaMapEngine, cinemaMapData, cinemaMapViewport, cinemaMapAssets, worldMap] = await Promise.all([
    readFile(new URL("../app/components/CinemaMapGame.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/CinemaWorldMap.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/MovieGeoTicket.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/components/CinemaMapHud.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/data/cinema-map-engine.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/data/cinema-map-data.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/data/cinema-map-viewport.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/data/cinema-map-assets.json", import.meta.url), "utf8"),
    readFile(new URL("../app/data/world-map-countries.json", import.meta.url), "utf8"),
  ]);

  assert.match(page, /<GameMenu/);
  assert.match(page, /<GameMenuConsole/);
  assert.match(menu, /export function GameMenu/);
  assert.match(menu, /GAME_TITLE = "Reel Challenge!"/);
  assert.match(menu, /New run/i);
  assert.match(menu, /Select game/i);
  assert.match(menu, /title: "Find the Director"/);
  assert.match(menu, /title: "Release Timeline"/);
  assert.match(menu, /title: "Cast Call"/);
  assert.match(menu, /title: "Cinema Map"/);
  assert.match(page, /attemptAssignment/);
  assert.match(page, /directorAtPoint/);
  assert.match(page, /resolveAssignment\(drag\.filmId, targetDirectorId, drag\.startPosition\)/);
  const dragMoveSource = page.slice(page.indexOf("const moveDragging"), page.indexOf("const stopDragging"));
  assert.match(dragMoveSource, /drag\.element\.style\.transform/);
  assert.doesNotMatch(dragMoveSource, /setPositions/);
  assert.doesNotMatch(dragMoveSource, /getBoundingClientRect/);
  assert.match(page, /onPointerCancel=\{cancelDragging\}/);
  assert.match(page, /onLostPointerCapture=\{cancelDragging\}/);
  assert.doesNotMatch(page, /onPointerCancel=\{stopDragging\}/);
  assert.match(page, /isReceiving=\{Boolean\(draggingFilmId\)\}/);
  assert.match(page, /setSelectedFilmId\(drag\.filmId\)/);
  assert.match(page, /returnPosition\?: Position/);
  assert.match(page, /setPositions\(\(current\) => \(\{ \.\.\.current, \[filmId\]: returnPosition \}\)\)/);
  assert.match(page, /ticket stays on the table and remains playable/);
  assert.doesNotMatch(page, /wrongMovieReappearDelay|poofingFilmId/);
  assert.match(page, /newlyVisibleMovieIds/);
  assert.match(page, /launchCoinReward\(outcome\.coinsAwarded/);
  assert.match(page, /outcome\.comboBonusCoins/);
  assert.match(page, /outcome\.multiplier/);
  assert.match(page, /startNextStage\(game\)/);
  assert.match(page, /<StageResultsOverlay\s+game=\{game\}/);
  assert.match(page, /game\.stageNumber === 2/);
  assert.match(page, /game\.stageNumber === 3/);
  assert.match(page, /game\.stageNumber === 4/);
  assert.match(page, /<ReleaseTimelineStage/);
  assert.match(page, /<ReleaseTimelineHud/);
  assert.match(page, /completeTimelineStage/);
  assert.match(page, /<ReleaseTimelineResults/);
  assert.match(page, /<CastCallGame/);
  assert.match(page, /<CastCallHud/);
  assert.match(page, /completeCastCallStage/);
  assert.match(page, /<CinemaMapGame/);
  assert.match(page, /<CinemaMapProgressHud/);
  assert.match(page, /completeCinemaMapStage/);
  assert.match(page, /hintContextFilmId/);
  assert.match(page, /hintContextDirectorId/);
  assert.match(page, /purchaseDirectorHint/);
  assert.match(page, /buyDirectorHint/);
  assert.match(page, /reopenDirectorHint/);
  assert.match(page, /dossierFilmId/);
  assert.match(page, /openDossier/);
  assert.match(page, /<MovieDossierOverlay/);
  assert.match(page, /pressure-\$\{isDirectorStage \? Math\.min\(GAME_CONFIG\.maximumActiveDirectors, Math\.max\(1, game\.activeDirectorIds\.length\)\) : 1\}/);
  assert.match(page, /wrongStreakRef\.current >= 4/);
  assert.match(page, /hintRescueCooldownMoveRef\.current = outcome\.state\.moveCount \+ 8/);
  assert.match(page, /setHintRescueVisible\(true\)/);
  assert.match(page, /setAutoOpenHint\(\{ filmId: targetFilmId, type \}\)/);
  assert.match(page, /setLastHintByFilm/);
  assert.match(page, /1200/);
  assert.match(page, /<CoinRewardLayer events=\{coinRewards\}/);
  assert.match(page, /directorCounterRef/);
  assert.match(page, /getBoundingClientRect/);
  assert.match(page, /requestAnimationFrame/);
  assert.match(page, /<DirectorArrivalFx event=\{menuView \? null : directorArrival\}/);
  assert.match(page, /arrivalImpactOrder=/);
  assert.match(page, /animateDirectorConveyor/);
  assert.match(page, /startRects\.forEach/);
  assert.match(page, /element\.animate/);
  assert.match(page, /slice\(completedSlotIndex \+ 1\)/);
  assert.match(page, /game\.directorSlots\[slotIndex\]/);
  assert.match(page, /stage-start-announcement/);
  assert.match(page, /startInReference=\{tutorialCompleted\}/);
  assert.match(page, /setArchiveSequence\(/);
  assert.match(page, /playSound\("punch"\)/);
  assert.match(page, /\[50, 130, 210\]\.forEach/);
  assert.match(page, /schedule\(\(\) => \{[\s\S]*?const conveyorStarts[\s\S]*?applyOutcome\(outcome\);\s*animateDirectorConveyor\(conveyorStarts\);\s*setActionLocked\(false\)/);
  assert.match(page, /isArchiving=\{archiveSequence\?\.directorId === directorId\}/);
  assert.match(page, /<CompletionArchiveSequence directorName=\{archiveSequence\.directorName\} filmTitles=\{archiveSequence\.filmTitles\}/);
  assert.doesNotMatch(page, /completionBurst|completion-burst|completion-ticket/);
  assert.match(page, /screenSticker=/);
  assert.match(page, /Genre key/i);
  assert.match(page, /GENRE_LEGEND\.map/);
  assert.match(page, /Color equals genre: Romance pink, Comedy yellow, Drama blue, Horror red, Sci-Fi cyan, Fantasy green, Crime and Thriller purple/);
  assert.doesNotMatch(page, /ticket-trailer|trailer-overlay/);
  assert.doesNotMatch(page, /selectedDirector|correctDirectorId|auto.?fil/i);
  assert.match(shell, /className="crt-tv"/);
  assert.match(shell, /className="crt-screen"/);
  assert.match(shell, /className="crt-scanlines" aria-hidden="true"/);
  assert.match(cards, /ticket-stickers/);
  assert.match(cards, /is-new/);
  assert.match(cards, /isLatest=\{sticker\.type === lastHintType\}/);
  assert.doesNotMatch(cards, /onMouseEnter=.*HintContext/);
  assert.doesNotMatch(cards, /onFocusCapture=.*HintContext/);
  assert.doesNotMatch(cards, /onHintContext/);
  assert.match(cards, /onClick=\{\(\) => onSelect\(film\.id\)\}/);
  assert.match(cards, /aria-pressed=\{isSelected\}/);
  assert.match(cards, /PUNCH_HOLE_POSITIONS/);
  assert.match(cards, /runtime\.punchCount/);
  assert.match(cards, /"--ticket-hole-mask": punchMask \|\| "linear-gradient\(#000 0 0\)"/);
  assert.match(cards, /ticket-punches/);
  assert.match(cards, /No match · Punched/);
  assert.match(cards, /director-sockets/);
  assert.match(cards, /director-context-button/);
  assert.match(cards, /Open director hints for/);
  assert.match(cards, /Open file \+/);
  assert.match(cards, /Open movie file/);
  assert.match(cards, /onOpenDossier/);
  assert.match(cards, /director-socket/);
  assert.match(cards, /data-drop-target="false"/);
  assert.match(cards, /data-drop-target="director"/);
  assert.match(cards, /data-socket-count=\{socketCount\}/);
  assert.match(cards, /is-arrival-impact/);
  assert.match(cards, /--arrival-impact-order/);
  assert.match(cards, /isHighlighted = dropState === "neutral" && !isFilled/);
  assert.match(cards, /const displayGenre = genreFamily\(film\.genre\)/);
  assert.match(cards, /"--ticket-accent": genreColor\(film\.genre\)/);
  assert.doesNotMatch(cards, /film\.accent/);
  assert.match(cards, /className="ticket-meta"/);
  assert.match(cards, /runtime\.hints\.releaseDate/);
  assert.match(cards, /DATE \?/);
  assert.match(cards, /className="ticket-dossier"/);
  assert.doesNotMatch(cards, /className="ticket-year"/);
  assert.match(cards, /<span>\{film\.title\}<\/span><small>\{film\.year\}<\/small>/);
  assert.match(cards, /`\$\{film\.title\} \(\$\{film\.year\}\)`/);
  assert.doesNotMatch(cards, /waiting_for_director|Hold for a future slot/);
  assert.doesNotMatch(cards, /sticker-frames|commons\.wikimedia\.org/);
  assert.match(dossier, /role="dialog" aria-modal="true"/);
  assert.match(dossier, /event\.key === "Escape"/);
  assert.match(dossier, /event\.key === "Tab"/);
  assert.match(dossier, /closeButtonRef\.current\?\.focus\(\)/);
  assert.match(dossier, /Movie evidence file/);
  assert.match(dossier, /dossier-placeholder/);
  assert.match(dossier, /dossier-director-row/);
  assert.match(dossier, /Release date/);
  assert.match(dossier, /Emergency answer/);
  assert.match(dossier, /no move/i);
  assert.match(dossier, /youtube-nocookie\.com\/embed/);
  assert.match(dossier, /decoding="async"/);
  assert.match(dossier, /draggable=\{false\}/);
  assert.match(dossier, /commons\.wikimedia\.org\/w\/api\.php/);
  assert.match(tutorial, /Drag this movie ticket onto the Director\./);
  assert.match(tutorial, /<MovieTicket/);
  assert.match(tutorial, /<DirectorSlot/);
  assert.match(tutorial, /setPointerCapture/);
  const tutorialDragMoveSource = tutorial.slice(tutorial.indexOf("const moveDragging"), tutorial.indexOf("const finishCorrectMatch"));
  assert.match(tutorialDragMoveSource, /drag\.element\.style\.transform/);
  assert.doesNotMatch(tutorialDragMoveSource, /setPositions/);
  assert.doesNotMatch(tutorialDragMoveSource, /getBoundingClientRect/);
  assert.match(tutorial, /finishWrongMatch/);
  assert.match(tutorial, /director-complete/);
  assert.match(tutorial, /Try free Movie Hint/);
  assert.match(tutorial, /Try free Director Hint/);
  assert.match(tutorial, /This one’s on us/);
  assert.match(tutorial, /tutorial-guidance-strip/);
  assert.match(tutorial, /RELEASE HERE/);
  assert.match(tutorial, /CLICK HERE TO REVEAL THE DATE/);
  assert.match(tutorial, /CLICK HERE TO OPEN THE DIRECTOR CLUE/);
  assert.match(tutorial, /Quick reference/);
  assert.match(tutorial, /Later Stages introduce new cinema challenges/);
  assert.doesNotMatch(tutorial, /tutorial-ticket-fan|tutorial-board-slots|GAME_LOOP_BEATS/);
  assert.match(timeline, /TIMELINE_CARD_COUNT = 7/);
  assert.match(timeline, /TIMELINE_POINTS_PER_CORRECT = 500/);
  assert.match(timeline, /Choose your starting point/);
  assert.match(timeline, /isCorrectGap/);
  assert.match(timeline, /correctGapIndex/);
  assert.match(timeline, /onPointerDown=\{startDragging\}/);
  assert.match(timeline, /onClick=\{\(\) => placeAt/);
  assert.match(timeline, /DATE \?/);
  assert.match(timeline, /movies you encountered in Stage 1/i);
  assert.match(timeline, /DECADE FINDER/);
  assert.match(timeline, /decadeMarkers/);
  assert.match(timeline, /scrollIntoView/);
  assert.match(timeline, /movies.*currently filed in this span/);
  assert.match(timeline, /WRONG POSITION/);
  assert.match(timeline, /WrongPlacementMotion/);
  assert.match(timeline, /target\.animate/);
  assert.match(timeline, /isResolving/);
  assert.match(styles, /\.timeline-gap\.is-wrong/);
  assert.match(styles, /\.timeline-status\.is-wrong/);
  assert.match(castCallGame, /currentActorId/);
  assert.match(castCallGame, /setPointerCapture/);
  assert.match(castCallGame, /onPointerCancel=\{cancelDragging\}/);
  assert.match(castCallGame, /onLostPointerCapture=\{cancelDragging\}/);
  assert.match(castCallGame, /onChoose=\{\(event\) =>/);
  assert.match(castCallGame, /ArrowLeft/);
  assert.match(castCallGame, /CastCallResults/);
  assert.doesNotMatch(castCallGame, /actor-grid|actor-pile|unresolvedActors\.map/);
  assert.match(castCallCards, /actor-polaroid/);
  assert.match(castCallCards, /Portrait placeholder for/);
  assert.match(castCallCards, /completedActors\.map/);
  assert.doesNotMatch(castCallCards, /movie\.cast\.map/);
  assert.match(castCallHud, /Replay Cast Call/);
  assert.match(castCallHud, /First-try casts/);
  assert.match(castCallEngine, /failedActorSpacing: 2/);
  assert.match(castCallEngine, /status: "retryPause"/);
  assert.match(castCallEngine, /enteringMovieId/);
  assert.match(castCallEngine, /status !== "awaitingInput"/);
  assert.match(castCallEngine, /validCastMovieIds/);
  assert.match(castCallEngine, /reserveMovieIds/);
  assert.match(castCallData, /The Matrix/);
  assert.match(castCallData, /portrait\?: string/);
  assert.match(styles, /\.cast-call-stage \{[^}]*position: relative;[^}]*touch-action: none/);
  assert.match(styles, /@keyframes cast-camera-flash/);
  assert.match(styles, /@keyframes polaroid-wrong/);
  assert.match(styles, /@keyframes cast-movie-enter/);
  assert.match(styles, /@media \(max-width: 560px\)[\s\S]*?\.cast-call-stage \{[^}]*grid-template-rows: auto 330px 205px auto/);
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.cast-camera-flash \{ display: none; \}/);
  assert.match(cinemaMapGame, /resolveCinemaMapPlacement/);
  assert.match(cinemaMapGame, /countryAtClientPoint/);
  assert.match(cinemaMapGame, /onPointerCancel=\{cancelDragging\}/);
  assert.match(cinemaMapGame, /CinemaMapResults/);
  assert.match(cinemaWorldMap, /viewBox=\{`0 0 \$\{MAP_VIEWBOX_WIDTH\} \$\{MAP_VIEWBOX_HEIGHT\}`\}/);
  assert.match(cinemaWorldMap, /data-country-id=\{country\.id\}/);
  assert.match(cinemaWorldMap, /aria-label=\{country\.name\}/);
  assert.match(cinemaWorldMap, /nearestSmallCountry/);
  assert.match(cinemaWorldMap, /onWheel=\{handleWheel\}/);
  assert.match(cinemaWorldMap, /Choose country by name/);
  assert.match(cinemaWorldMap, /World view/i);
  assert.match(movieGeoTicket, /movie-geo-ticket/);
  assert.match(movieGeoTicket, /COUNTRY OF ORIGIN · CLASSIFIED/);
  assert.match(cinemaMapHud, /YOUR CINEMA JOURNEY|Your cinema journey/);
  assert.match(cinemaMapHud, /Travel again/);
  assert.match(cinemaMapEngine, /PRIMARY_COUNTRY/);
  assert.match(cinemaMapEngine, /ANY_VALID_COUNTRY/);
  assert.match(cinemaMapEngine, /maximumAttempts: 3/);
  assert.match(cinemaMapEngine, /status !== "awaitingPlacement"/);
  assert.match(cinemaMapData, /id: "dogtooth"/);
  assert.match(cinemaMapData, /primaryCountry: "GR"/);
  assert.match(cinemaMapViewport, /MAP_MAX_SCALE = 7/);
  assert.match(cinemaMapViewport, /nearestSmallCountry/);
  assert.equal(JSON.parse(cinemaMapAssets).length, 8);
  const parsedWorldMap = JSON.parse(worldMap);
  assert.equal(parsedWorldMap.source.license, "Public domain");
  assert.ok(parsedWorldMap.countries.length >= 200);
  assert.ok(["GR", "KR", "FR", "JP", "MX", "IT", "IR", "US"].every((id) => parsedWorldMap.countries.some((country) => country.id === id)));
  assert.match(styles, /\.director-board-screen\.mode-cinema-map/);
  assert.match(styles, /\.cinema-map-viewport \{[^}]*touch-action: none/);
  assert.match(styles, /@media \(max-width: 560px\)[\s\S]*?\.cinema-map-stage/);
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.movie-geo-ticket\.is-correct/);
  assert.match(hud, /HINT_TYPES\.map/);
  assert.match(hud, /DIRECTOR_HINT_TYPES\.map/);
  assert.match(hud, /DIRECTOR HINTS/);
  assert.match(hud, /MOVIE HINTS/);
  assert.match(hud, /Hints for:/);
  assert.match(hud, /hintContextFilm\?\.title/);
  assert.match(hud, /hintContextDirector\?\.name/);
  assert.match(hud, /director-hint-reveal/);
  assert.match(hud, /Build a director file without revealing the three movie answers/);
  assert.match(hud, /hintRescueVisible/);
  assert.match(hud, /Four misses—try one clue/);
  assert.match(hud, /className="hint-price"/);
  assert.match(hud, /Small clue · Reveal the movie's release year/);
  assert.match(hud, /Strong clue · When their directing voice emerged/);
  assert.match(hud, /STAGE \{game\.stageNumber\}/);
  assert.match(hud, /DIRECTORS \{stageVictories\}/);
  assert.match(hud, /`\$\{cost\} ●`/);
  assert.match(hud, /hintCostForMovie/);
  assert.match(hud, /canUseEliminationHint/);
  assert.match(hud, /USE AGAIN/);
  assert.match(hud, /ONE CANDIDATE LEFT/);
  assert.match(hud, /EMERGENCY ANSWER/);
  assert.match(hud, /PANIC OPTION/);
  assert.match(hud, /GAME_CONFIG\.emergencyAnswerScoreMultiplier/);
  assert.match(hud, /is-emergency/);
  assert.doesNotMatch(hud, /Board pressure|capacity-panel|victory-panel|VictoryChip/);
  assert.match(hud, /releaseDate: \{ icon: "#", name: "Release date"/);
  assert.match(hud, /no move spent/i);
  assert.match(hud, /arrivalState = isCleanup \? "cleanup"/);
  assert.match(hud, /arrival-\$\{arrivalState\}/);
  assert.match(hud, /multiplier-badge/);
  assert.match(hud, /ON FIRE/);
  assert.match(hud, /STEAMING/);
  assert.match(hud, /CLEANUP · \{game\.visibleMovieIds\.length\} LEFT/);
  assert.match(hud, /Solved tickets will not be replaced/);
  assert.match(hud, /LAST TICKETS ENTERING/);
  assert.match(hud, /game\.stagePhase === "cleanup"/);
  assert.match(hud, /aria-live="polite"/);
  assert.match(hud, /isLastSafeMove = !isCleanup && !isFinalReelsPending && directorCount === GAME_CONFIG\.maximumActiveDirectors - 1 && game\.nextDirectorIn === 1/);
  assert.match(hud, /next-director-panel/);
  assert.match(hud, /Last safe move · Clear a director now/);
  assert.match(hud, /Choose this movie&apos;s director/);
  assert.match(hud, /Assign \$\{selectedFilm\.title\} to/);
  assert.match(hud, /hint-shop-intro/);
  assert.match(hud, /aria-atomic="true"/);
  assert.match(coinFx, /Array\.from\(\{ length: event\.amount \}/);
  assert.match(coinFx, /COIN_STAGGER_MS/);
  assert.match(coinFx, /event\.bonusAmount/);
  assert.match(coinFx, /coin-combo-pop/);
  assert.match(coinFx, /FROM ×/);
  assert.match(completionArchive, /3 films matched/i);
  assert.match(completionArchive, /filmTitles\.slice\(0, 3\)\.map/);
  assert.match(completionArchive, /ARCHIVED/);
  assert.match(completionArchive, /Filed · Moving on/);
  assert.doesNotMatch(rankPopup, /rank-rays/);
  assert.match(stageResults, /Stage completed!/);
  assert.match(stageResults, /Stage score/);
  assert.match(stageResults, /Total score/);
  assert.match(stageResults, /Best combo/);
  assert.match(stageResults, /Highest multiplier/);
  assert.match(stageResults, /Reward bay/);
  assert.match(stageResults, /window\.setInterval/);
  assert.match(engine, /coinsAwarded: config\.correctMatchCoins \+ comboBonusCoins/);
  assert.match(engine, /coinsAwarded: 0/);
  assert.match(engine, /punchCount: movie\.punchCount \+ 1/);
  assert.match(engine, /newlyVisibleMovieIds: \[\]/);
  assert.doesNotMatch(engine, /waiting_to_reappear|wrongMovieReappearDelay/);
  assert.match(engine, /visibleMovieCount:\s*10/);
  assert.match(engine, /maximumActiveDirectors:\s*5/);
  assert.match(engine, /initialDirectorCountdown:\s*3/);
  assert.match(engine, /directorCountdownProgression:\s*\[3\]/);
  assert.match(engine, /stageDifficultyMixes:\s*STAGE_DIFFICULTY_MIXES/);
  assert.match(engine, /tieredDirectorOrder\(eligible, random, config\)/);
  assert.match(difficulty, /DIRECTOR_DIFFICULTY_TIERS/);
  assert.match(difficulty, /This is a playtest hypothesis/);
  assert.match(difficulty, /accessible:\s*6, familiar:\s*3, challenging:\s*1, archive:\s*0/);
  assert.match(difficulty, /accessible:\s*0, familiar:\s*2, challenging:\s*4, archive:\s*4/);
  assert.match(engine, /releaseDate:\s*2/);
  assert.match(engine, /stageDirectorCount:\s*10/);
  assert.doesNotMatch(engine, /targetDirectorCompletions/);
  assert.match(engine, /startingCoins:\s*4/);
  assert.match(engine, /comboTwoMultiplierAt:\s*4/);
  assert.match(engine, /comboThreeMultiplierAt:\s*6/);
  assert.match(engine, /comboTwoCoinBonus:\s*1/);
  assert.match(engine, /comboThreeCoinBonus:\s*2/);
  assert.match(engine, /status: "stage_complete"/);
  assert.match(engine, /export function startNextStage/);
  assert.match(engine, /function appendDirectorSlot/);
  assert.match(engine, /initialDirectorSlots\(\[\.\.\.packedDirectors, directorId\], slots\.length\)/);
  assert.match(engine, /export function completeTimelineStage/);
  assert.match(engine, /export function completeCinemaMapStage/);
  assert.match(engine, /stageSet\.has\(movie\.ownerDirectorId\)/);
  assert.match(engine, /eliminationHintCosts:\s*\[2, 3, 5\]/);
  assert.match(engine, /emergencyAnswerScoreMultiplier:\s*0\.5/);
  assert.match(engine, /directorHintCosts/);
  assert.match(engine, /export function purchaseDirectorHint/);
  assert.match(engine, /directorHints:/);
  assert.match(engine, /movie\.hints\.directAnswer \? config\.emergencyAnswerScoreMultiplier : 1/);
  assert.match(engine, /Correct director: \$\{owner\.name\}/);
  assert.match(engine, /type !== "elimination" && movie\.hints\[type\]/);
  assert.match(engine, /directorId !== movie\.ownerDirectorId/);
  assert.match(engine, /remainingDirectorCandidates/);
  assert.match(directorHints, /origin: "Origin"/);
  assert.match(directorHints, /careerPeriod: "Career period"/);
  assert.match(directorHints, /genreTendency: "Genre tendency"/);
  assert.match(directorHints, /thematicDNA: "Thematic DNA"/);
  assert.match(directorHints, /styleNote: "Style note"/);
  assert.match(directorHints, /knownFor: "Known for"/);
  assert.equal((directorHints.match(/^ {2}"?[a-z0-9-]+"?: profile\(/gm) ?? []).length, 60);
  assert.equal((genreColors.match(/^ {2}["A-Z]/gm) ?? []).length, 7);
  assert.match(genreColors, /Romance: "#ff7eb6"/);
  assert.match(genreColors, /Comedy: "#ffd84a"/);
  assert.match(genreColors, /Drama: "#5d8dff"/);
  assert.match(genreColors, /Horror: "#ff504e"/);
  assert.match(genreColors, /"Sci-Fi": "#61eee0"/);
  assert.match(genreColors, /Fantasy: "#8fdc62"/);
  assert.match(genreColors, /"Crime\/Thriller": "#b07cff"/);
  assert.equal((engine.match(/title: "/g) ?? []).length, 6);
  assert.match(styles, /\.crt-tv\s*\{/);
  assert.match(styles, /\.crt-screen\s*\{/);
  assert.match(styles, /aspect-ratio:\s*16\s*\/\s*9/);
  assert.match(styles, /height:\s*100dvh/);
  assert.doesNotMatch(styles, /\.crt-screen\s*\{[^}]*min-height:\s*clamp\(610px/s);
  assert.match(styles, /pointer-events:\s*none/);
  assert.match(styles, /\.director-slot\.is-empty\s*\{[^}]*pointer-events:\s*none/s);
  assert.match(styles, /\.director-slot\.is-active\.is-receiving\s*\{/);
  assert.match(styles, /\.director-slot\.is-active\.is-neutral\s+\.director-socket\.is-open/);
  assert.match(styles, /\.director-slot\.is-archiving\s*\{[^}]*animation:\s*director-archive-exit/s);
  assert.match(styles, /\.director-socket\.is-ready/);
  assert.doesNotMatch(styles, /\.director-board-screen\s*\{[^}]*touch-action:\s*none/s);
  assert.match(styles, /contain:\s*layout paint/);
  assert.match(styles, /\.genre-rule/);
  assert.match(styles, /\.screen-bottom-sticker/);
  assert.doesNotMatch(styles, /\.screen-instruction|\.on-air-bug/);
  assert.match(styles, /\.director-board-screen::before, \.director-board-screen::after/);
  assert.match(styles, /animation:\s*pressure-smoke-drift 22s ease-in-out infinite alternate/);
  assert.match(styles, /@keyframes pressure-smoke-drift/);
  assert.doesNotMatch(styles.match(/@keyframes pressure-smoke-drift \{[\s\S]*?\n\}/)?.[0] ?? "", /background-position/);
  assert.match(styles, /@keyframes director-arrival-flight\s*\{[^}]*translate3d\(var\(--arrival-start-x\)/s);
  assert.doesNotMatch(styles.match(/@keyframes director-arrival-flight \{[^}]*\}/)?.[0] ?? "", /\bleft:|\btop:/);
  assert.match(styles, /@keyframes coin-flight\s*\{[^}]*translate3d\(var\(--coin-start-x\)/s);
  assert.match(styles, /\.hint-panel\.is-rescue\s*\{[^}]*animation:\s*hint-shop-rescue 1s ease-in-out 4/s);
  assert.match(styles, /\.hint-sticker\.is-new\s*\{[^}]*animation:\s*hint-sticker-plop/s);
  assert.doesNotMatch(styles, /\.movie-ticket:(?:hover|focus)[^,{]*\.hint-sticker\.is-latest \.hint-sticker-popover/);
  assert.doesNotMatch(styles, /\.movie-ticket\.is-selected \.hint-sticker\.is-latest \.hint-sticker-popover/);
  assert.match(styles, /\.hint-context\.has-movie strong/);
  assert.match(styles, /\.hint-context\.has-director strong/);
  assert.match(styles, /\.director-hint-reveal/);
  assert.match(styles, /\.director-slot\.is-selected/);
  assert.match(styles, /\.dossier-layer/);
  assert.match(styles, /\.movie-dossier/);
  assert.match(styles, /\.dossier-placeholder/);
  assert.match(styles, /\.dossier-director-row/);
  assert.match(styles, /\.hint-price b/);
  assert.match(styles, /\.hint-grid button\.is-repeatable/);
  assert.match(styles, /\.hint-grid button\.is-emergency/);
  assert.match(styles, /\.hint-grid button\.is-emergency \.hint-icon/);
  assert.match(styles, /\.score-panel\.multiplier-2 \.multiplier-badge/);
  assert.match(styles, /\.score-panel\.multiplier-3 \.multiplier-badge/);
  assert.match(styles, /\.next-director-panel\.arrival-warm/);
  assert.match(styles, /\.next-director-panel\.arrival-hot/);
  assert.match(styles, /\.next-director-panel\.arrival-critical/);
  assert.match(styles, /\.next-director-display strong\s*\{[^}]*color:\s*var\(--arrival-color\)/s);
  assert.match(styles, /\.archive-ticket-stage\s*\{[^}]*animation:\s*archive-stack-flight/s);
  assert.match(styles, /@keyframes archive-ticket-snap/);
  assert.match(styles, /@keyframes archive-punch-hit/);
  assert.match(styles, /@keyframes archive-stack-flight/);
  assert.match(styles, /@keyframes director-archive-exit/);
  assert.doesNotMatch(styles, /rank-rays|rays-spin|completion-burst|completion-ticket/);
  assert.doesNotMatch(styles, /\.capacity-leds/);
  assert.match(styles, /\.stage-results-overlay/);
  assert.match(styles, /\.stage-score-transfer/);
  assert.match(styles, /\.stage-results-grid/);
  assert.match(styles, /\.coin-combo-pop/);
  assert.match(styles, /@keyframes hint-sticker-plop/);
  assert.match(styles, /@keyframes hint-shop-rescue/);
  assert.match(styles, /\.ticket-meta\s*\{/);
  assert.doesNotMatch(styles, /\.ticket-meta[^}]*display:\s*none/s);
  assert.match(styles, /\.director-mini-stack button small/);
  assert.equal((styles.match(/animation:[^;{}]*infinite/g) ?? []).length, 5);
  assert.match(styles, /\.next-director-panel\.is-last-safe\s*\{[^}]*animation:\s*next-director-safe-pulse 2s ease-in-out infinite/s);
  assert.doesNotMatch(styles, /@keyframes crt-noise/);
  assert.match(styles, /\.interactive-tutorial-board/);
  assert.match(styles, /\.tutorial-director-target/);
  assert.match(styles, /@keyframes tutorial-ticket-focus/);
  assert.match(styles, /@keyframes tutorial-director-target/);
  assert.match(styles, /\.hint-grid button:disabled:not\(\.is-owned\)/);
  assert.match(styles, /\.tutorial-board-stage/);
  assert.doesNotMatch(styles, /\.tutorial-action-popup/);
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.interactive-tutorial-board/);
  assert.match(styles, /\.stage-progress-line/);
  assert.match(styles, /\.stage-start-announcement/);
  assert.match(styles, /\.timeline-stage/);
  assert.match(styles, /\.timeline-film-card/);
  assert.match(styles, /\.timeline-gap/);
  assert.match(styles, /\.timeline-decade-guide/);
  assert.match(styles, /\.timeline-decade-scale/);
  assert.match(styles, /\.timeline-film-card > b\s*\{[^}]*font-size:\s*clamp\(17px/s);
  assert.match(styles, /\.hint-grid small\s*\{[^}]*overflow-wrap:\s*anywhere/s);
  assert.match(styles, /@keyframes ticket-plop/);
  assert.match(styles, /@keyframes ticket-reject-return/);
  assert.match(styles, /@keyframes ticket-punch-in/);
  assert.match(styles, /\.ticket-punches i/);
  assert.match(styles, /\.movie-ticket::before[^}]*-webkit-mask-image:\s*var\(--ticket-hole-mask\)[^}]*mask-composite:\s*intersect/s);
  assert.doesNotMatch(styles, /\.movie-ticket\.is-rejected[^}]*opacity:\s*0/s);
  assert.match(directorArrivalFx, /createPortal/);
  assert.match(directorArrivalFx, /director-arrival-flight/);
  assert.match(directorArrivalFx, /--arrival-start-x/);
  assert.match(hud, /next-director-panel[^\n]*is-launching/);
  assert.match(hud, /ref=\{directorCounterRef\}/);
  assert.match(styles, /@keyframes director-arrival-flight/);
  assert.match(styles, /@keyframes director-arrival-destination/);
  assert.match(styles, /@keyframes director-arrival-impact/);
  assert.match(styles, /@keyframes director-counter-launch/);
  assert.match(styles, /\.director-slot\.is-arrival-impact/);
  assert.doesNotMatch(styles, /@keyframes director-plop/);
  assert.match(styles, /@keyframes coin-flight/);
  assert.match(styles, /@keyframes coin-readout-pop/);
  assert.match(styles, /\.director-board-screen\.pressure-1/);
  assert.match(styles, /\.director-board-screen\.pressure-2/);
  assert.match(styles, /\.director-board-screen\.pressure-3/);
  assert.match(styles, /\.director-board-screen\.pressure-4/);
  assert.match(styles, /\.director-board-screen\.pressure-5/);
  assert.match(styles, /@keyframes next-director-safe-pulse/);
  assert.match(styles, /@keyframes next-director-safe-pulse[\s\S]*?background-color:\s*#66333a/);
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.next-director-panel\.is-last-safe\s*\{[^}]*animation:\s*none/s);
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.director-arrival-flight\s*\{[^}]*display:\s*none/s);
  assert.match(styles, /\.director-slots\s*\{[^}]*top:\s*clamp\(116px,\s*27\.5%,\s*160px\)/s);
  assert.match(styles, /@keyframes rank-pop/);
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)/);
  assert.doesNotMatch(styles, /\.score-meter/);
  assert.equal((data.match(/name: "/g) ?? []).length, 10);
  assert.equal((expanded.match(/^ {2}d\(/gm) ?? []).length, 50);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
});
